#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2', '>= 1.0.0'
cookbook 'postgresql', '>=3.3.4'
cookbook 'database', '>=1.5.2'
cookbook 'nodejs', '>=1.3.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
